### PR TITLE
Prepare for Python 3.8 migration 

### PR DESCRIPTION
**Pull request by jan-janssen**
Found during testing yaff for python 3.8 compatibility. 
https://github.com/conda-forge/yaff-feedstock/pull/4

### CODE REVIEW

**Comment by tovrstra** [comment]
@jan-janssen Thanks for fixing this! This breaks Python 2.7 compatibility, which is fine by me. @lvduyfhu @SvenRogge: do we have remaining use cases with Py2.7?

**Comment by lvduyfhu** [comment]
@jan-janssen @tovrstra @SvenRogge I have completely shifted to python 3, so for me this is fine.

**Comment by tovrstra** [comment]
I'm currently in a situation that I need to maintain 2.7 compatibility for historical reasons. When the tests pass, I'll merge.

**Comment by jan-janssen** [comment]
From the changes suggested in the pull request I created a patch for the conda packages: https://github.com/conda-forge/molmod-feedstock/blob/master/recipe/python38.patch Still to get the pip version of molmod Python 3.8 compatible, it would be nice if you could merge these changes.

**Comment by tovrstra** [comment]
I'm going to reopen a copy of this PR since I cannot push any further to it.

**Pull request closed without merging**
